name: example
description: An example of using `simple_property_observer`
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  simple_property_observer: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.4
  simple_property_observer_builder:
    path: ../simple_property_observer_builder

