name: example
description: An example of using `simple_property_observer`
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  simple_property_observer:
    path: ../simple_property_observer

dev_dependencies:
  simple_property_observer_builder:
    path: ../simple_property_observer_builder
