name: simple_property_observer
description: A simple Dart package for observing property changes. Also known as property changed notifier. See also `simple_property_observer_builder` package.
version: 1.0.0
repository: https://github.com/ibako/simple_property_observer

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.17.5
