builders:
  property_observable:
    target: ":property_observable_generator"
    import: "package:simple_property_observer_builder/builder.dart"
    builder_factories: ["propertyObservableFactory"]
    build_extensions: {".dart": [".property_observable.g.dart"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
